"""Writes tools/tls-host/tests/fixtures.rs: keys and signatures made by
OpenSSL, for checking the kernel's RSA and ECDSA verifiers on the host."""

import os
import subprocess
import tempfile

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "tools", "tls-host", "tests", "fixtures.rs")
KERNEL_OUT = os.path.join(ROOT, "kernel", "src", "tls", "vectors.rs")
MESSAGE = b"AerOS TLS signature check message 0123456789"


def run(args, **kwargs):
    return subprocess.run(args, check=True, capture_output=True, **kwargs).stdout


def rsa_case(directory, bits, hash_name, mode):
    key = os.path.join(directory, "k%d.pem" % bits)
    if not os.path.exists(key):
        run(["openssl", "genpkey", "-algorithm", "RSA", "-pkeyopt", "rsa_keygen_bits:%d" % bits, "-out", key])
    message = os.path.join(directory, "m.bin")
    open(message, "wb").write(MESSAGE)
    args = ["openssl", "dgst", "-" + hash_name, "-sign", key]
    if mode == "pss":
        size = {"sha256": 32, "sha384": 48}[hash_name]
        args += ["-sigopt", "rsa_padding_mode:pss", "-sigopt", "rsa_pss_saltlen:%d" % size]
    signature = run(args + [message])
    modulus = run(["openssl", "rsa", "-in", key, "-modulus", "-noout"]).decode().strip().split("=")[1]
    return ("rsa", mode, hash_name, modulus.lower(), "010001", signature.hex())


def ec_case(directory, curve, hash_name):
    key = os.path.join(directory, "e-%s.pem" % curve)
    if not os.path.exists(key):
        run(["openssl", "genpkey", "-algorithm", "EC", "-pkeyopt", "ec_paramgen_curve:" + curve, "-out", key])
    message = os.path.join(directory, "m.bin")
    open(message, "wb").write(MESSAGE)
    signature = run(["openssl", "dgst", "-" + hash_name, "-sign", key, message])
    der = run(["openssl", "pkey", "-in", key, "-pubout", "-outform", "DER"])
    size = 65 if curve == "prime256v1" else 97
    return ("ec", curve, hash_name, der[-size:].hex(), "", signature.hex())


def main():
    cases = []
    with tempfile.TemporaryDirectory() as directory:
        for bits in (2048, 4096):
            for hash_name in ("sha256", "sha384"):
                cases.append(rsa_case(directory, bits, hash_name, "pkcs1"))
                cases.append(rsa_case(directory, bits, hash_name, "pss"))
        for curve in ("prime256v1", "secp384r1"):
            for hash_name in ("sha256", "sha384"):
                for _ in range(2):
                    os.remove(os.path.join(directory, "e-%s.pem" % curve)) if os.path.exists(os.path.join(directory, "e-%s.pem" % curve)) else None
                    cases.append(ec_case(directory, curve, hash_name))
    lines = [
        "// Generated by tools/make-tls-fixtures.py with OpenSSL. Do not edit.",
        "",
        "pub struct Case {",
        "    pub kind: &'static str,",
        "    pub variant: &'static str,",
        "    pub hash: &'static str,",
        "    pub key: &'static str,",
        "    pub exponent: &'static str,",
        "    pub signature: &'static str,",
        "}",
        "",
        "pub const MESSAGE: &[u8] = b\"%s\";" % MESSAGE.decode(),
        "",
        "pub const CASES: &[Case] = &[",
    ]
    for kind, variant, hash_name, key, exponent, signature in cases:
        lines += [
            "    Case {",
            '        kind: "%s",' % kind,
            '        variant: "%s",' % variant,
            '        hash: "%s",' % hash_name,
            '        key: "%s",' % key,
            '        exponent: "%s",' % exponent,
            '        signature: "%s",' % signature,
            "    },",
        ]
    lines.append("];")
    open(OUT, "w", newline="\n").write("\n".join(lines) + "\n")
    print("wrote", len(cases), "cases to", OUT)

    wanted = [
        ("rsa", "pkcs1", "sha256"),
        ("rsa", "pss", "sha256"),
        ("ec", "prime256v1", "sha256"),
        ("ec", "secp384r1", "sha384"),
    ]
    picked = [next(case for case in cases if case[:3] == key) for key in wanted]
    kernel = [
        "// Generated by tools/make-tls-fixtures.py with OpenSSL. Do not edit.",
        "",
        "pub struct Vector {",
        "    pub kind: &'static str,",
        "    pub variant: &'static str,",
        "    pub hash: &'static str,",
        "    pub key: &'static str,",
        "    pub signature: &'static str,",
        "}",
        "",
        "pub const MESSAGE: &[u8] = b\"%s\";" % MESSAGE.decode(),
        "",
        "pub const VECTORS: &[Vector] = &[",
    ]
    for kind, variant, hash_name, key, exponent, signature in picked:
        kernel += [
            "    Vector {",
            '        kind: "%s",' % kind,
            '        variant: "%s",' % variant,
            '        hash: "%s",' % hash_name,
            '        key: "%s",' % key,
            '        signature: "%s",' % signature,
            "    },",
        ]
    kernel.append("];")
    open(KERNEL_OUT, "w", newline="\n").write("\n".join(kernel) + "\n")
    print("wrote", len(picked), "vectors to", KERNEL_OUT)


main()
