"""Writes tools/tls-host/tests/chain_data.rs: certificate chains made by
OpenSSL (root, optional intermediate, leaf) in several key and hash
combinations, with the leaf keys so the host tests can run a real server."""

import os
import tempfile

import tlspki

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "tools", "tls-host", "tests", "chain_data.rs")


def main():
    cases = []
    with tempfile.TemporaryDirectory() as directory:
        make = lambda *args, **kwargs: cases.append(tlspki.chain(directory, *args, **kwargs))
        make("rsa-rsa-rsa", "rsa", "sha256", ("rsa", "sha384"), "rsa", "sha384")
        make("ec-p384-ec", "p256", "sha384", ("p384", "sha384"), "p256", "sha256")
        make("rsa-ec-ec", "rsa", "sha256", ("p256", "sha256"), "p256", "sha256")
        make("direct-ed25519", "p256", "sha256", None, "ed25519", "sha256")
        make("not-a-ca", "p256", "sha256", ("p256", "sha256"), "p256", "sha256", tlspki.NOT_A_CA)
        make("other-root", "p256", "sha256", None, "p256", "sha256")
    lines = [
        "// Generated by tools/make-tls-chains.py with OpenSSL. Test keys only. Do not edit.",
        "",
        "pub struct Chain {",
        "    pub name: &'static str,",
        "    pub root: &'static str,",
        "    pub middle: &'static str,",
        "    pub leaf: &'static str,",
        "    pub chain_pem: &'static str,",
        "    pub leaf_pem: &'static str,",
        "    pub leaf_key_pem: &'static str,",
        "}",
        "",
        "pub const CHAINS: &[Chain] = &[",
    ]
    for case in cases:
        lines += [
            "    Chain {",
            '        name: "%s",' % case["name"],
            '        root: "%s",' % case["root"].hex(),
            '        middle: "%s",' % case["middle"].hex(),
            '        leaf: "%s",' % case["leaf"].hex(),
            '        chain_pem: r#"%s"#,' % case["intermediate_pem"],
            '        leaf_pem: r#"%s"#,' % case["leaf_pem"],
            '        leaf_key_pem: r#"%s"#,' % case["leaf_key_pem"],
            "    },",
        ]
    lines.append("];")
    open(OUT, "w", newline="\n").write("\n".join(lines) + "\n")
    print("wrote", len(cases), "chains")


main()
