"""Writes kernel/src/tls/roots.rs from the Mozilla CA list bundled with pip
(pip/_vendor/certifi/cacert.pem). Only each root's subject name and public
key are kept; the kernel does not check a root's own signature or validity.
Roots with key types the kernel cannot verify (anything but RSA of at least
2048 bits, P-256 and P-384) are left out."""

import base64
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "kernel", "src", "tls", "roots.rs")


def bundle_path():
    if len(sys.argv) > 1:
        return sys.argv[1]
    import pip._vendor.certifi as certifi

    return certifi.where()


def read_tlv(data, at):
    tag = data[at]
    first = data[at + 1]
    if first < 0x80:
        length, header = first, 2
    else:
        count = first & 0x7F
        length = int.from_bytes(data[at + 2 : at + 2 + count], "big")
        header = 2 + count
    return tag, at + header, at + header + length


def children(data, start, end):
    at = start
    while at < end:
        tag, value_start, value_end = read_tlv(data, at)
        yield tag, at, value_start, value_end
        at = value_end


OID_RSA = bytes.fromhex("2a864886f70d010101")
OID_EC = bytes.fromhex("2a8648ce3d0201")
OID_P256 = bytes.fromhex("2a8648ce3d030107")
OID_P384 = bytes.fromhex("2b81040022")


def split_certificate(der):
    _, start, end = read_tlv(der, 0)
    _, tbs_start, tbs_end = read_tlv(der, start)
    fields = list(children(der, tbs_start, tbs_end))
    if fields[0][0] == 0xA0:
        fields = fields[1:]
    subject = fields[4]
    spki = fields[5]
    return der[subject[1] : subject[3]], der[spki[1] : spki[3]], spki


def supported(der, spki_info):
    _, at, _, _ = spki_info
    spki_start = spki_info[1]
    spki_end = spki_info[3]
    parts = list(children(der, spki_info[2], spki_end))
    algorithm = parts[0]
    oid_tag, oid_start, oid_end = read_tlv(der, algorithm[2])
    oid = der[oid_start:oid_end]
    if oid == OID_RSA:
        bits = der[parts[1][2] + 1 : parts[1][3]]
        _, k_start, _ = read_tlv(bits, 0)
        _, n_start, n_end = read_tlv(bits, k_start)
        modulus = bits[n_start:n_end].lstrip(b"\x00")
        return "RSA-%d" % (len(modulus) * 8) if len(modulus) * 8 >= 2048 else None
    if oid == OID_EC:
        _, c_start, c_end = read_tlv(der, oid_end)
        curve = der[c_start:c_end]
        return {OID_P256: "P-256", OID_P384: "P-384"}.get(curve)
    return None


def literal(data):
    return 'b"' + "".join("\\x%02x" % byte for byte in data) + '"'


def main():
    text = open(bundle_path(), encoding="utf-8").read()
    entries = []
    skipped = []
    position = 0
    for match in re.finditer(r"-----BEGIN CERTIFICATE-----(.*?)-----END CERTIFICATE-----", text, re.S):
        header = text[position : match.start()]
        position = match.end()
        der = base64.b64decode("".join(match.group(1).split()))
        label = re.findall(r"^# Label:\s*\"?(.*?)\"?\s*$", header, re.M)
        name = (label[-1] if label else "unnamed root").replace('"', "'")
        subject, spki, spki_info = split_certificate(der)
        kind = supported(der, spki_info)
        if kind is None:
            skipped.append(name)
            continue
        entries.append((name, kind, subject, spki))
    entries.sort(key=lambda entry: entry[0].lower())
    lines = [
        "// Generated by tools/make-tls-roots.py from the Mozilla CA list. Do not edit.",
        "",
        "use super::x509::TrustAnchor;",
        "",
        "pub static ROOTS: &[TrustAnchor] = &[",
    ]
    for name, kind, subject, spki in entries:
        lines.append("    // %s (%s)" % (name, kind))
        lines.append("    TrustAnchor {")
        lines.append("        subject: %s," % literal(subject))
        lines.append("        spki: %s," % literal(spki))
        lines.append("    },")
    lines.append("];")
    open(OUT, "w", newline="\n").write("\n".join(lines) + "\n")
    print("wrote %d roots (%d skipped: unsupported key type)" % (len(entries), len(skipped)))
    for name in skipped:
        print("  skipped:", name)


main()
