"""Regenerates kernel/src/pkg_vectors.rs: signed test packages for the package
manager's boot-test. Needs OpenSSL on PATH. The keys are throwaway and exist
only to sign these vectors."""

import hashlib
import os
import subprocess
import tempfile

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "kernel", "src", "pkg_vectors.rs")

HELLO_V1 = b"#!aeros\necho hello v1\n"
HELLO_V2 = b"#!aeros\necho hello v2\n"
HELLO_V3 = b"#!aeros\necho hello v3\n"
README_V1 = b"demo package 1.0.0\n"
README_V2 = b"demo package 1.1.0\n"
README_V3 = b"demo package 1.2.0\n"


def build(name, version, files, claimed_hash=None, claimed_size=None):
    lines = ["AEROSPKG1", f"name={name}", f"version={version}"]
    data = b""
    for path, mode, content in files:
        digest = claimed_hash or hashlib.sha256(content).hexdigest()
        size = claimed_size if claimed_size is not None else len(content)
        lines.append(f"file={path};{mode:o};{size};{digest}")
        data += content
    return ("\n".join(lines) + "\ndata\n").encode() + data


def generate_key(directory, name):
    pem = os.path.join(directory, name + ".pem")
    subprocess.run(["openssl", "genpkey", "-algorithm", "ed25519", "-out", pem], check=True)
    der = subprocess.run(
        ["openssl", "pkey", "-in", pem, "-pubout", "-outform", "DER"],
        check=True,
        capture_output=True,
    ).stdout
    return pem, der[-32:]


def sign(directory, pem, payload):
    source = os.path.join(directory, "payload")
    signature = os.path.join(directory, "signature")
    with open(source, "wb") as handle:
        handle.write(payload)
    subprocess.run(
        ["openssl", "pkeyutl", "-sign", "-rawin", "-inkey", pem, "-in", source, "-out", signature],
        check=True,
    )
    with open(signature, "rb") as handle:
        return handle.read()


def rust_bytes(name, data, kind="&[u8]"):
    body = ", ".join(str(byte) for byte in data)
    return f"pub const {name}: {kind} = &[{body}];\n"


def main():
    with tempfile.TemporaryDirectory() as directory:
        pem, key = generate_key(directory, "trusted")
        other_pem, _ = generate_key(directory, "other")
        v1 = build("demo", "1.0.0", [("bin/hello", 0o755, HELLO_V1), ("share/doc/readme.txt", 0o644, README_V1)])
        v2 = build("demo", "1.1.0", [("bin/hello", 0o755, HELLO_V2), ("share/doc/readme.txt", 0o644, README_V2)])
        v3 = build("demo", "1.2.0", [("bin/hello", 0o755, HELLO_V3), ("share/doc/readme.txt", 0o644, README_V3)])
        bad_hash = build("bad", "9.0.0", [("bin/x", 0o755, b"payload")], claimed_hash="00" * 32)
        traversal = build("evil", "1.0.0", [("../escape", 0o644, b"x")])
        truncated = build("short", "1.0.0", [("bin/x", 0o755, b"payload")], claimed_size=500)
        out = ["//! Generated by tools/make-pkg-vectors.py - do not edit.\n\n"]
        out.append(f"pub const KEY: [u8; 32] = {list(key)};\n")
        for name, content in (
            ("HELLO_V1", HELLO_V1),
            ("HELLO_V2", HELLO_V2),
            ("README_V1", README_V1),
        ):
            out.append(rust_bytes(name, content))
        for name, payload in (
            ("V1", v1),
            ("V2", v2),
            ("V3", v3),
            ("BAD_HASH", bad_hash),
            ("TRAVERSAL", traversal),
            ("TRUNCATED", truncated),
        ):
            out.append(rust_bytes(name, payload))
            out.append(rust_bytes(name + "_SIG", sign(directory, pem, payload)))
        out.append(rust_bytes("V1_SIG_OTHER", sign(directory, other_pem, v1)))
        update_image = bytes((i * 37 + 11) & 0xFF for i in range(3000))
        out.append(rust_bytes("UPDATE_IMAGE", update_image))
        out.append(rust_bytes("UPDATE_IMAGE_SIG", sign(directory, pem, update_image)))
        out.append(rust_bytes("UPDATE_IMAGE_SIG_OTHER", sign(directory, other_pem, update_image)))
        with open(OUT, "w", newline="\n") as handle:
            handle.write("".join(out))
    print("wrote", OUT)


main()
